<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 *
 * @author Stefano Torresi (http://stefanotorresi.it)
 * @license See the file LICENSE.txt for copying permission.
 * ************************************************
 */

$this->layout()->bodyClass = 'login';

$form = $this->loginForm;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url('admin/login'),
    'method' => 'post',
    'id' => 'login-form',
));

$form->get('identity')
     ->setAttributes([ 'class' => 'input-block-level', 'required' => true ]);

$form->get('credential')
     ->setAttributes([ 'class' => 'input-block-level', 'required' => true ]);

$form->get('submit')
     ->setAttribute('class', 'btn btn-large btn-primary')
     ->setLabel('Login');

$this->formElementErrors()->setAttributes(array('class' => 'form-errors'));

?>

<?= $this->form()->openTag($form) ?>

    <?= $this->ztbFormElement($form->get('identity')) ?>
    <?= $this->ztbFormElement($form->get('credential')) ?>

    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?= $this->escapeHtmlAttr($this->redirect) ?>" />
    <?php endif ?>

    <div class="control-group">
        <?= $this->formButton($form->get('submit')) ?>
    </div>

<?= $this->form()->closeTag() ?>

<?= $this->authFailed ?
    '<div class="auth-ko alert alert-error">Autenticazione fallita. Riprovare.</div>'
    : '';
?>
