<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @author Stefano Torresi (http://stefanotorresi.it)
 * @license See the file LICENSE.txt for copying permission.
 * ************************************************
 */

use Zend\Mvc\Controller\Plugin\FlashMessenger;

if ($this->flashMessenger()->hasCurrentErrorMessages()) {
    $errorMessages = $this->flashMessenger()->getCurrentErrorMessages();
    $this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_ERROR);
} else {
    $errorMessages = $this->flashMessenger()->getErrorMessages();
}

if ($this->flashMessenger()->hasCurrentSuccessMessages()) {
    $successMessages = $this->flashMessenger()->getCurrentSuccessMessages();
    $this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_SUCCESS);
} else {
    $successMessages = $this->flashMessenger()->getSuccessMessages();
}

?>

<?php if ($errorMessages) : ?>
    <div class="alert fade in alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4 class="alert-heading">Oops!</h4>
        <ul>
        <?php
        foreach ($errorMessages as $errorMessage) :
            echo sprintf("<li>%s</li>", $this->escapeHtml($errorMessage));
        endforeach;
        ?>
        </ul>
    </div>
<?php endif; ?>

<?php if ($successMessages) : ?>
    <div class="alert fade in alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4 class="alert-heading">Ok!</h4>
        <ul>
            <?php
            foreach ($successMessages as $successMessage) :
                echo sprintf("<li>%s</li>", $this->escapeHtml($successMessage));
            endforeach;
            ?>
        </ul>
    </div>
<?php endif; ?>
