<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this *
 * @author Stefano Torresi (http://stefanotorresi.it)
 * @license See the file LICENSE.txt for copying permission.
 * ************************************************
 */

$this->placeHolder('title')->set('<h2 class="title">'.$this->escapeHtml($this->layout()->title).'</h2>');

if ($this->isGranted('admin-dashboard')) {
    $this->placeHolder('title')->setPrefix('<div class="span6">')->setPostfix('</div>');
}

$this->placeHolder('nav-lang')->captureStart();
if ($this->layout()->i18nEnabled) :
    ?>
    <div class="btn-group">
        <button class="btn btn-small dropdown-toggle" data-toggle="dropdown">
            <?= ucfirst(Locale::getDisplayLanguage(Locale::getDefault())) ?>
            <span class="caret"></span>
        </button>
        <?= $this->navigation()->menu()->renderMenu('nav-lang', array('ulClass' => 'nav-lang dropdown-menu')) ?>
    </div>
    <?php
endif;
$this->placeHolder('nav-lang')->captureEnd();

?>
<header id="header">

    <div class="row-fluid">

        <?= $this->placeHolder('title') ?>

        <?php if ($this->isGranted('admin-dashboard')) : ?>

        <nav id="nav-secondary" class="span6">
            <?= $this->placeHolder('nav-lang') ?>
            <div class="btn-group">
                <a class="btn btn-success btn-small btn-icon-text"
                   href="<?= $this->url($this->layout()->frontendRoute) ?>">
                    <i class="icon-home icon-white"></i>
                    <span> Frontend</span>
                </a>
                <a class="btn btn-info btn-small btn-icon-text"
                   href="<?= $this->url($this->layout()->backendRoute) ?>">
                    <i class="icon-cog icon-white"></i>
                    <span> Backend</span>
                </a>
                <a class="btn btn-danger btn-small btn-icon-text"
                   href="<?= $this->url('admin/logout'); ?>">
                    <i class="icon-off icon-white"></i>
                    <span> Logout</span>
                </a>
            </div>
        </nav>

        <?php else : ?>
            <nav class="text-center">
                <?= $this->placeHolder('nav-lang') ?>
            </nav>
        <?php endif; ?>

    </div>

    <?php if ($this->isGranted('admin-dashboard')) : ?>


    <nav id="nav-backend" class="navbar">
        <div class="navbar-inner">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="nav-collapse collapse">
                <?= $this->ztbnavigation('MyBackend\Navigation\BackendNavigation')->ztbmenu()->setMaxDepth(1) ?>
            </div>
        </div>
    </nav>

    <nav id="breadcrumbs">
        <?= $this->ztbnavigation('MyBackend\Navigation\BackendBreadcrumbs')->ztbbreadcrumbs()->setTranslator(
                $this->plugin('translate')->getTranslator(),
                'MyBackend'
            ); ?>
    </nav>

    <?= $this->partial('my-backend/partial/flash-messenger') ?>

    <?php endif; ?>

</header><!-- #header -->
