<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this *
 * @author Stefano Torresi (http://stefanotorresi.it)
 * @license See the file LICENSE.txt for copying permission.
 * ************************************************
 */

$logoutUrl = $this->url(
    'zfcuser/logout',
    array(),
    array(
        'query' => array(
            'redirect' => $this->url($this->routes['backend']),
        )
    )
);

$this->placeHolder('title')->set('<h2 class="title">'.$this->escapeHtml($this->layout()->title).'</h2>');

if ($this->isGranted('admin')) {
    $this->placeHolder('title')->setPrefix('<div class="span6">')->setPostfix('</div>');
}

$this->placeHolder('nav-lang')->captureStart();
if ($this->layout()->displayLangNav) :
    ?>
    <div class="btn-group">
        <button class="btn btn-small dropdown-toggle" data-toggle="dropdown">
            <?= ucfirst(Locale::getDisplayLanguage($this->layout()->lang)) ?>
            <span class="caret"></span>
        </button>
        <?= $this->navigation()->menu()->renderMenu('nav-lang', array('ulClass' => 'nav-lang dropdown-menu')) ?>
    </div>
    <?php
endif;
$this->placeHolder('nav-lang')->captureEnd();

?>
<header id="header">

    <div class="row-fluid">

        <?= $this->placeHolder('title') ?>

        <?php if ($this->isGranted('admin')) : ?>

        <nav id="nav-secondary" class="span6">
            <?= $this->placeHolder('nav-lang') ?>
            <div class="btn-group">
                <a class="btn btn-success btn-small btn-icon-text"
                   href="<?= $this->url($this->routes['frontend']) ?>">
                    <i class="icon-home icon-white"></i>
                    <span> Frontend</span>
                </a>
                <a class="btn btn-info btn-small btn-icon-text"
                   href="<?= $this->url($this->routes['backend']) ?>">
                    <i class="icon-cog icon-white"></i>
                    <span> Backend</span>
                </a>
                <a class="btn btn-danger btn-small btn-icon-text"
                   href="<?= $logoutUrl ?>">
                    <i class="icon-off icon-white"></i>
                    <span> Logout</span>
                </a>
            </div>
        </nav>

        <?php else : ?>
            <nav class="text-center">
                <?= $this->placeHolder('nav-lang') ?>
            </nav>
        <?php endif; ?>

    </div>

    <?php if ($this->isGranted('admin')) : ?>


    <nav id="nav-backend" class="navbar">
        <div class="navbar-inner">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="nav-collapse collapse">
                <?= $this->ztbnavigation('nav-backend')->ztbmenu()->setMaxDepth(1) ?>
            </div>
        </div>
    </nav>

    <nav id="breadcrumbs">
        <?= $this->ztbnavigation('nav-backend')->ztbbreadcrumbs(); ?>
    </nav>

    <?php
        $button = '<button type="button" class="close" data-dismiss="alert">&times;</button>';
        $this->flashMessenger()
            ->setMessageOpenFormat("<div%s>$button<ul><li>")
            ->setMessageCloseString('</li></ul></div>');

        echo $this->flashMessenger()->render('error', array('alert', 'alert-error', 'fade', 'in'));
        echo $this->flashMessenger()->render('success', array('alert', 'alert-success', 'fade', 'in'));
    ?>

    <?php endif; ?>

</header><!-- #header -->
