<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this *
 * @author Stefano Torresi (http://stefanotorresi.it)
 * @license See the file LICENSE.txt for copying permission.
 * ************************************************
 */

use Zend\Json\Json;

$applicationConfig = array(
    'homeUrl' => $this->url('admin', [], ['force_canonical' => true]),
);

echo $this->inlineScript()
        ->prependScript('app = new Backend('. Json::encode($applicationConfig) .');')
        ->prependFile($this->basePath('js/backend-scripts.js?') . $this->layout()->cacheBustIndex).PHP_EOL;

