<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this *
 * @author Stefano Torresi (http://stefanotorresi.it)
 * @license See the file LICENSE.txt for copying permission.
 * ************************************************
 */

if ($this->layout()->terminate()) {
    echo $this->content;

    return;
}

// metas
$this->headMeta()->appendName('viewport','width=device-width, initial-scale=1.0');

// common css
$this->headLink()
    ->prependStylesheet($this->basePath('/css/admin.css?'.$this->layout()->cache_bust_index), 'all')
    ->prependStylesheet('//fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic', 'all');

// these are the only scripts needed in the head
// any other script is included in at the bottom of the DOM, inside 'javascript.phtml' template
$this->headScript()->prependFile($this->basePath('js/header-scripts.js?').$this->layout()->cache_bust_index);

$bodyClass = (isset($this->error) ? 'error' : $this->layout()->bodyClass);

?>
<?= $this->doctype().PHP_EOL ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie10 lt-ie9 lt-ie8 lt-ie7" lang="<?= Locale::getDefault() ?>"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie10 lt-ie9 lt-ie8" lang="<?= Locale::getDefault() ?>"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie10 lt-ie9" lang="<?= Locale::getDefault() ?>"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10" lang="<?= Locale::getDefault() ?>"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="<?= Locale::getDefault() ?>"> <!--<![endif]-->
<head>
    <?= $this->headTitle($this->layout()->title)->setSeparator(' | ').PHP_EOL ?>
    <?= $this->headMeta()->setCharset('utf-8').PHP_EOL; ?>
    <?= $this->headLink().PHP_EOL ?>
    <?= $this->headScript().PHP_EOL ?>
</head>

<body class="<?= $this->escapeHtmlAttr($bodyClass) ?>">

<a id="top"></a>

<!--[if lt IE 7]>
<div class="chromeframe text-center">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</div>
<![endif]-->

<div class="container-fluid">

    <div id="wrapper">
        <?= $this->header ?>

        <section id="content">

            <?= $this->content ?>

        </section>

        <?= $this->footer ?>
    </div><!-- #wrapper -->

</div><!-- .container-fluid -->

<?= $this->javascript ?>

</body>
</html>
